querying_lab/querying_lab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab/', include('school_db.urls')),
    path('', RedirectView.as_view(url='/lab/'))
]

querying_lab/school_db/urls.py
from django.urls import path
from . import views


app_name = 'lab'
urlpatterns = [
    path('', views.index, name="index"),
    path('one/', views.problem_one, name="one"),
    path('two/', views.problem_two, name="two"),
    path('three/', views.problem_three, name="three"),
    path('four/', views.problem_four, name="four"),
    path('five/', views.problem_five, name="five"),
    path('six/', views.problem_six, name="six")
]

querying_lab/school_db/models.py
from django.db import models

# Create your models here.

class Instructor(models.Model):
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    hire_date = models.DateField()

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

class Student(models.Model):
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    year = models.IntegerField(default=9)
    gpa = models.FloatField()

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

class Course(models.Model):
    name = models.CharField(max_length=40)
    instructor = models.ForeignKey(Instructor, null=True, blank=True, on_delete=models.SET_NULL)
    credits = models.IntegerField()

    def __str__(self) -> str:
        return self.name

class StudentCourse(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    grade = models.CharField(max_length=20)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['student', 'course'], name='unique_student_course')
        ]

    def __str__(self) -> str:
        return f'{self.student} - {self.course}'

querying_lab/school_db/views.py
from django.shortcuts import render
from .models import Student, Instructor, Course, StudentCourse


def index(request):
    students = Student.objects.all()

    # The following line creates a list that allows you to examine the data 
    # from a Queryset in an easier to visualize way
    # It is not required for functionality!
    # Place a breakpoint on line 14, then compare 'students' and 'data_visualization'
    data_visualization = [item for item in students]

    context = {
        'students': students
    }
    return render(request, 'school/index.html', context)

def problem_one(request):
    # Find all students who have a GPA greater than 3.0. 
    # Order the data by highest GPAs first.
    students = Student.objects.filter(gpa__gte = 3)

    context = {
        'students': students
    }
    return render(request, 'school/one.html', context)

def problem_two(request):
    # Find all instructors hired prior to 2010
    # Order by hire date
    instructors = Instructor.objects.filter(hire_date__lt='2010-01-01').order_by('-hire_date')

    context = {
        'instructors': instructors
    }
    return render(request, 'school/two.html', context)

def problem_three(request):
    # Find all students who have a A+ in any class and are NOT getting a C+ in any class. 
    # Order the data by student's first name alphabetically.
    students_with_c= Student.objects.filter(studentcourse__grade='C+')
    students_with_no_c = StudentCourse.objects.filter(grade='A+').exclude(student_id__in=students_with_c).order_by('student_id__first_name')
    data_visualization = [item for item in students_with_no_c]

    context = {
        'students_with_no_c': students_with_no_c
    }
    return render(request, 'school/three.html', context)

def problem_four(request):
    # Find all students who are taking the Programming class. 
    # Order by their grade. 
    student_courses = StudentCourse.objects.filter(course__name='Programming').order_by('grade')
    data_visualization = [item for item in student_courses]

    context = {
        'student_courses': student_courses
    }
    return render(request, 'school/four.html', context)

def problem_five(request):
    # Find all students getting an A in the Programming class. 
    # Order by last name.
    student_courses =StudentCourse.objects.filter(course__name='Programming', grade='A').order_by('student')
    context = {
        'student_courses': student_courses
    }
    return render(request, 'school/five.html', context)

def problem_six(request):
    # Find all students with a GPA less than 3.0 who are getting an A in Programming class.
    # Order by GPA.
    student_courses = StudentCourse.objects.filter(course__name='Programming', grade='A', student__gpa__lt=3.0)
    data_visualization = [item for item in student_courses]

    context = {
        'student_courses': student_courses
    }
    return render(request, 'school/six.html', context)

################## BONUS #################
# These problems will require using Aggregate functions along with annotate()
# https://docs.djangoproject.com/en/4.0/topics/db/aggregation/
# https://docs.djangoproject.com/en/4.0/ref/models/querysets/#annotate

# Create a view function and template for each bonus problem you complete

# BONUS ONE
# Write a query to find any instructors who are only teaching one single course. Display the instructor and the course

# BONUS TWO
# Display all students along with the number of credits they are taking

# BONUS THREE
# Find all students who are getting an A in any course and average their GPAs. Display the number of students and their Average GPA

# BONUS FOUR
# Write a function that will replace student GPAs in the database with an accurate score based only on their current grades
# This may require multiple queries
# See https://www.indeed.com/career-advice/career-development/gpa-scale for a chart of what point value each grade is worth

querying_lab/school_db/templates/school/five.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Problem Five</title>
</head>
<body>
    <h1>All Students With A In Programming, Ordered By Last Name</h1>
    <table class="center-table">
        <thead>
            <tr>
                <th>Last Name</th><th>First Name</th><th>Grade</th>
            </tr>
        </thead>
        <tbody>
            {% for student in student_courses %}
            <tr>
                <td>{{ student.student.last_name }}</td><td>{{student.student.first_name}}</td><td>{{ student.course.name }}</td><td>{{ student.grade }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

querying_lab/school_db/templates/school/four.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Problem Four</title>
</head>
<body>
    <h1>Programming Students</h1>
    <table class="center-table">
        <thead>
            <tr>
                <th>First Name</th><th>Last Name</th><th>Grade</th>
            </tr>
        </thead>
        <tbody>
            {% for item in student_courses %}
            <tr>
                <td>{{item.student.first_name}}</td><td>{{item.student.last_name}}</td><td>{{item.grade}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

querying_lab/school_db/templates/school/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>devCodeCamp Django Querying Lab</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body>
    <h1 class="center-text">devCodeCamp Django Querying Lab</h2>
    <nav>
        <ul>
            <li><a href="{% url 'lab:one' %}">Problem One</a></li>
            <li><a href="{% url 'lab:two' %}">Problem Two</a></li>
            <li><a href="{% url 'lab:three' %}">Problem Three</a></li>
            <li><a href="{% url 'lab:four' %}">Problem Four</a></li>
            <li><a href="{% url 'lab:five' %}">Problem Five</a></li>
            <li><a href="{% url 'lab:six' %}">Problem Six</a></li>
        </ul>
    </nav>
    <div class="center-text">
        <h2>List of all Students:</h2>
        <table class="center-table">
            <thead>
                <tr>
                    <th>First Name</th><th>Last Name</th><th>GPA</th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <tr>
                    <td>{{student.first_name}}</td><td>{{student.last_name}}</td><td>{{student.gpa}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    
</body>
</html>

querying_lab/school_db/templates/school/one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Problem One</title>
</head>
<body>
    <h1>All Students With GPA Higher Than 3.0 Ordered By Highest First</h1>
    <table class="center-table">
        <thead>
            <tr>
                <th>First Name</th><th>GPA</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
            <tr>
                <td>{{student.first_name}}</td><td>{{student.gpa}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

querying_lab/school_db/templates/school/six.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Problem Six</title>
</head>
<body>
    <h1>Great Programmers under 3.0</h1>
    <table class="center-table">
        <thead>
            <tr>
                <th>First Name</th><th>Last Name</th><th>Grade</th>
            </tr>
        </thead>
        <tbody>
            {% for student in student_courses %}
            <tr>
                <td>{{student.student.first_name}}</td><td>{{student.student.last_name}}</td><td>{{student.grade}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

querying_lab/school_db/templates/school/three.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Problem Three</title>
</head>
<body>
    <h1>Students With A+</h1> 
    <h1>Programming Students</h1>
    <table class="center-table">
        <thead>
            <tr>
                <th>First Name</th><th>Last Name</th><th>Grade</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students_with_no_c %}
            <tr>
                <td>{{student.student.first_name}}</td><td>{{student.student.last_name}}</td><td>{{student.grade}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

querying_lab/school_db/templates/school/two.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Problem Two</title>
</head>
<body>
    <h1>Instructors Hired Before 2010</h1>
    <table class="center-table">
        <thead>
            <tr>
                <th>First Name</th><th>Last Name</th><th>Hire Date</th>
            </tr>
        </thead>
        <tbody>
            {% for instructor in instructors %}
            <tr>
                <td>{{instructor.first_name}}</td><td>{{instructor.last_name}}</td><td>{{instructor.hire_date}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
   
</body>
</html>